[package]
name = "sigil-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
sigil-rules-basic = { path = "../sigil-rules-basic" }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }
blake3 = { workspace = true }
globset = { workspace = true }
dunce = { workspace = true }
rusqlite = { workspace = true }
hdrhistogram = { workspace = true }
parking_lot = { workspace = true }
data-encoding = { workspace = true }
ed25519-dalek = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
rand_core = { version = "0.6", features = ["std"] }
insta = { workspace = true }
proptest = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }
